//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetSupport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetSupport.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active session detected.
        /// </summary>
        internal static string activeSession {
            get {
                return ResourceManager.GetString("activeSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything seems fine, you may try to connect now..
        /// </summary>
        internal static string allFine {
            get {
                return ResourceManager.GetString("allFine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bound.
        /// </summary>
        internal static string bound {
            get {
                return ResourceManager.GetString("bound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some components report an error. Please fix them..
        /// </summary>
        internal static string componentError {
            get {
                return ResourceManager.GetString("componentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string connect {
            get {
                return ResourceManager.GetString("connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed. Please try again or contact your assistant..
        /// </summary>
        internal static string connectionFailed {
            get {
                return ResourceManager.GetString("connectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully connected. Your assistant may now log into your box..
        /// </summary>
        internal static string connectionOk {
            get {
                return ResourceManager.GetString("connectionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string disconnect {
            get {
                return ResourceManager.GetString("disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect first.
        /// </summary>
        internal static string disconnectFirst {
            get {
                return ResourceManager.GetString("disconnectFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully disconnected. Your assistant will not be able to access your box until you reconnect again..
        /// </summary>
        internal static string disconnectOk {
            get {
                return ResourceManager.GetString("disconnectOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        internal static string loginFailed {
            get {
                return ResourceManager.GetString("loginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login data faulty.
        /// </summary>
        internal static string loginFault {
            get {
                return ResourceManager.GetString("loginFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string paused {
            get {
                return ResourceManager.GetString("paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string running {
            get {
                return ResourceManager.GetString("running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not log into support server.
        ///
        ///Maybe you entered the wrong login data?.
        /// </summary>
        internal static string serverLoginError {
            get {
                return ResourceManager.GetString("serverLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to set a windows password, please enter below..
        /// </summary>
        internal static string setWinPw {
            get {
                return ResourceManager.GetString("setWinPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking....
        /// </summary>
        internal static string srvChecking {
            get {
                return ResourceManager.GetString("srvChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support server not found, please try again..
        /// </summary>
        internal static string srvNotFound {
            get {
                return ResourceManager.GetString("srvNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting.
        /// </summary>
        internal static string starting {
            get {
                return ResourceManager.GetString("starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Changing.
        /// </summary>
        internal static string statusChanging {
            get {
                return ResourceManager.GetString("statusChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are still connected. Please disconnect first..
        /// </summary>
        internal static string stillConnected {
            get {
                return ResourceManager.GetString("stillConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string stopped {
            get {
                return ResourceManager.GetString("stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping.
        /// </summary>
        internal static string stopping {
            get {
                return ResourceManager.GetString("stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A support assistant is connected, his session will be dropped if you disconnect now.
        ///
        ///Really disconnect?.
        /// </summary>
        internal static string supporterConnected {
            get {
                return ResourceManager.GetString("supporterConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal Server Start failed.
        /// </summary>
        internal static string termStartFailed {
            get {
                return ResourceManager.GetString("termStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start the Terminal Server.
        ///
        ///Maybe you are not logged in as administrator or you are using the wrong version of Windows?.
        /// </summary>
        internal static string termStartFailedMsg {
            get {
                return ResourceManager.GetString("termStartFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbound.
        /// </summary>
        internal static string unbound {
            get {
                return ResourceManager.GetString("unbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid username and password..
        /// </summary>
        internal static string validNamePw {
            get {
                return ResourceManager.GetString("validNamePw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password set failed.
        /// </summary>
        internal static string winPwSetFailed {
            get {
                return ResourceManager.GetString("winPwSetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please tell your assistant that you can&apos;t set a password..
        /// </summary>
        internal static string winPwSetFailedMsg {
            get {
                return ResourceManager.GetString("winPwSetFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
